### ISSUE TITLE
Adopt to new capistrano plugin system

### ISSUE THREAD

**Issue by ekho** [ekho/capistrano-git-submodule-strategy#15]
Discuss started at capistrano/capistrano#1572

**Comment by ekho** [comment]
https://github.com/capistrano/capistrano/pull/1572#issuecomment-222859456

**Comment by alto** [comment]
👍

**Comment by kevin-lot** [comment]
Capistrano 3.7 is out. ping @ekho

**Comment by ekho** [comment]
For Capistrano 3.7+ I created new plugin [capistrano-git-with-submodules](https://github.com/ekho/capistrano-git-with-submodules)

**Comment by alto** [comment]
Thanks @ekho, well done! 👍

**Comment by kevin-lot** [comment]
Thanks again.
