### ISSUE TITLE
LoadError: cannot load such file -- capistrano/git-submodule-strategy

### ISSUE THREAD

**Issue by gowthamgts** [ekho/capistrano-git-submodule-strategy#16]
I installed the plugin as per your instructions in my system and got the following:
```
$ cap staging deploy
(Backtrace restricted to imported tasks)
cap aborted!
LoadError: cannot load such file -- capistrano/git-submodule-strategy
C:/Users/Len/Desktop/area51/masstamilan-rails/Capfile:11:in `<top (required)>'
(See full trace by running task with --trace)
```

Can you please help with the same?

**Comment by ekho** [comment]
1. Did you add `gem 'capistrano-git-submodule-strategy', '~> 0.1', :github => 'ekho/capistrano-git-submodule-strategy'` to your `Gemfile`?
2. Did you run `bundle install` after updating `Gemfile`?
3. Did you add `require 'capistrano/git-submodule-strategy'` to `Capfile`?

**Comment by gowthamgts** [comment]
Yeah. Did exactly as the same.

**Comment by gowthamgts** [comment]
This is the line from bundle install log:

    Using capistrano-git-submodule-strategy 0.1.22 from git://github.com/ekho/capistrano-git-submodule-strategy.git (at master@f54d1f0)

**Comment by ekho** [comment]
Try to run capistrano throught bundle
`bundle exec cap staging deploy`

**Comment by gowthamgts** [comment]
That worked. What causes this problem? I have all the gems up to date.

**Comment by gowthamgts** [comment]
Think I got it [here](http://stackoverflow.com/a/6588708/2277817). Although, isn't it nice to use without appending `bundle exec`? :cry:

**Comment by ekho** [comment]
`bundle` executes capistrano in local environment where is `capistrano-git-submodule-strategy` installed.

if you are running `cap` directly it uses global ruby env, but there is no installed `capistrano-git-submodule-strategy`. Of course you can install it globally with `gem install capistrano-git-submodule-strategy`, but it is not true way =))

**Comment by gowthamgts** [comment]
Thanks for your time.

**Comment by ekho** [comment]
You are welcome
