### ISSUE TITLE
git_keep_meta is undocumented

### ISSUE THREAD

**Issue by schnittchen** [ekho/capistrano-git-submodule-strategy#7]
I'm setting it to true for a project of mine to avoid the "fatal: not a git repository" message with every bundler invocation.

I am not sure about the tradeoffs of this option.

**Comment by ekho** [comment]
can you run capistrano with flag --trace and then attach logs here?

**Comment by schnittchen** [comment]
What do you need to know? Maybe this suffices:

```
$ bundle exec rails console -e staging
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Loading staging environment (Rails 4.1.3)
```

I have a gem bundled as a submodule (using the :path option), which causes these messages when .git has been cleansed (probably in the submodule, did not check that).

**Comment by schnittchen** [comment]
And I confirm that it goes away with git_keep_meta set to true.

**Comment by ekho** [comment]
I'm not using rails, I'm using pure capistrano3.
I can not answer why `bundle exec rails console -e staging` fails =(

If you can run this command in debug mode you should see a stack trace.

**Comment by schnittchen** [comment]
Nothing is actually failing, sorry for being unclear. I get message on stdout, that's all.

The message comes when bundler is used, even without capistrano. Minimal reproduction:

```
bundle gem new
cd new/
bundle gem submodule
echo "gem 'submodule', path: 'submodule'" >> Gemfile
bundle
bundle console # fine
rm -rf .git
bundle console # error message
```

**Comment by ekho** [comment]
I reproduced your problem on clean new virtual machine WITHOUT capistrano-git-submodule-strategy.
I think this problem is not in git_keep_meta, bundler requires existing .git folder.

**Comment by schnittchen** [comment]
The message does NOT come from the submoduled gem's gemspec (the generated gemspec contains `spec.files         = `git ls-files -z`.split("\x0")`, replacing that did not help)

**Comment by ekho** [comment]
@schnittchen problem still reproducing ?

**Comment by schnittchen** [comment]
It looks like you added documentation in 8dc9ad28d279d8c8a1233dd6992581b1e6a6b159 :)

I just upgraded to 0.1.19. The mentioned warning messages during deploy disappeared a while ago when I started using the the option.
