### ISSUE TITLE
Duplicated commands caused by requiring 'capistrano/git'

### ISSUE THREAD

**Issue by favalex** [ekho/capistrano-git-submodule-strategy#8]
Hi Boris,

thanks for your work.

I'm using capistrano 3.4.0 and I've noticed that when using capistrano-git-submodule-strategy git commands are issued twice.

I think the problem is in capistrano itself, because it loads capistrano/git.rb instead of requiring it [1]. Every time git.rb is executed tasks are appended to the existing ones, hence the duplication.

 I plan to open an issue in capistrano too, but I was wondering:

1) do you have the same problem?
2) if yes, do you have a workaround?

Thanks

Gabriele

[1] https://github.com/capistrano/capistrano/blob/master/lib/capistrano/setup.rb#L16

**Comment by ekho** [comment]
Hi @favalex 

I don't have this problem. But some people has. I think #3 is a same problem. I closed it because I can't fix it in my plugin
