### ISSUE TITLE
It's not ignoring the folders defined in the .gitattributes

### ISSUE THREAD

**Issue by thiagolcks** [ekho/capistrano-git-submodule-strategy#9]
I'm trying to not deploy the folders defined in my .gitattributes but it's not working. Have a look in my file:
/tests   export-ignore
/bin     export-ignore

Is there another way to ignore some folders?

**Comment by ekho** [comment]
Hi, @thiagolcks 

`export-ignore` does not affects because git submodule strategy does not use `git archive` command.

Now you can use workaround: write custom capistrano task after `deploy:updating` which removes some files/directories from release

**Comment by thiagolcks** [comment]
Thanks!
